config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :categories
  resources :dashboard do
    collection do
      get 'in_draft'
    end
  end

  resources :adverts do
    collection do
      get 'to_draft'
    end
  end

  resources :users

  root to: "adverts#index"

  get '/in_draft' => "in_draft#dashboard"
  get '/to_draft' => "to_draft#adverts"

end

app/models/advert.rb
class Advert < ActiveRecord::Base
	extend Enumerize

	enumerize :status, :in => {:new_adv => 0, :draft => 1, :rejected => 2, :published => 3, :archive => 4}, scope: :having_status

	belongs_to :user
	belongs_to :category
	belongs_to :advert_type
	mount_uploader :image, ImageUploader
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :adverts
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :adverts
end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController
  before_action :set_advert, only: [:show, :edit, :update, :destroy]

  # GET /adverts
  # GET /adverts.json
  #def index
  #  @adverts = Advert.where(:status => "published")
  #  @categories = Category.all
  #  @q = Advert.ransack(params[:q])
  #  @adverts = @q.result(:distinct => true)
  #  @adverts = @adverts.paginate(:page => params[:page], :per_page => 5)
  #end

  def index
    @q = Advert.ransack(params[:q])
    @adverts = @q.result(:distinct => true)
    @adverts = @adverts.having_status(:published).paginate(:page => params[:page], :per_page => 5)
    @categories = Category.all
  end

  # GET /adverts/1
  # GET /adverts/1.json
  def show

  end

  # GET /adverts/new
  def new
    @advert = Advert.new
    img = Advert.new
    img = img.image
  end

  # GET /adverts/1/edit
  def edit
    @advstatus = "new_adv" || "archive"

  end

  # POST /adverts
  # POST /adverts.json
  def create
    @advert = Advert.new(advert_params)
    @advert.user_id = current_user.id

    respond_to do |format|
      if @advert.save
        format.html { redirect_to @advert, notice: 'Advert was successfully created.' }
        format.json { render :show, status: :created, location: @advert }
      else
        format.html { render :new }
        format.json { render json: @advert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adverts/1
  # PATCH/PUT /adverts/1.json
  def update
    respond_to do |format|
      if
        current_user.id != 2
        @advert.status = 'new_adv'
      else
      end

      if @advert.update(advert_params)
        format.html { redirect_to @advert, notice: 'Advert was successfully updated.' }
        format.json { render :show, status: :ok, location: @advert }
      else
        format.html { render :edit }
        format.json { render json: @advert.errors, status: :unprocessable_entity }
      end
    end
  end

  def upload
    uploader = ImageUploader.new
  end


  def to_draft
    redirect_to :back
  end


  # DELETE /adverts/1
  # DELETE /adverts/1.json
  def destroy
    @advert.destroy
    respond_to do |format|
      format.html { redirect_to adverts_url, notice: 'Advert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advert
      @advert = Advert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advert_params
      params.require(:advert).permit(:title, :description, :price, :user_id, :category_id, :image, :search, :status)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController


	def index
		@adverts = Advert.all
	    @categories = Category.all
    	@q = Advert.ransack(params[:q])
    	@adverts = @q.result(:distinct => true)
    	@adverts = @adverts.paginate(:page => params[:page], :per_page => 10)
	end

	def in_draft
		@adverts = Advert.all
		@adverts = @adverts.having_status(:draft)
	end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email)
    end
end

app/helpers/advert_types_helper.rb
module AdvertTypesHelper
end

app/helpers/adverts_helper.rb
module AdvertsHelper
end

app/helpers/adverttypes_helper.rb
module AdverttypesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/adverts/_admin_form.html.slim
div.col-md-6
  = simple_form_for(@advert, action: :upload, :html => {multipart: true}) do |f|
    - if @advert.errors.any?
      #error_explanation
        h2 = "#{pluralize(@advert.errors.count, "error")} prohibited this advert from being saved:"
        ul
          - @advert.errors.full_messages.each do |message|
            li = message

    .form-inputs
      = f.input :title
    .form-inputs
      = f.input :description
    .form-inputs
      = f.input :price
    .form-inputs
      = f.association :category    
    .form-inputs
      = f.input :adverttype, as: :select, collection: [ "Продажа", "Покупка", "Обмен", "Услуга", "Аренда"]
    .form-inputs
      = f.input :image, as: :file, multiple: true
    .form-inputs
      = f.select :status, Advert.status.options
    .form-actions
      = f.button :submit




      

app/views/adverts/_form.html.slim
div.col-md-6
  = simple_form_for(@advert, action: :upload, :html => {multipart: true}) do |f|
    - if @advert.errors.any?
      #error_explanation
        h2 = "#{pluralize(@advert.errors.count, "error")} prohibited this advert from being saved:"
        ul
          - @advert.errors.full_messages.each do |message|
            li = message

    .form-inputs
      = f.input :title
    .form-inputs
      = f.input :description
    .form-inputs
      = f.input :price
    .form-inputs
      = f.association :category
    .form-inputs
      = f.input :adverttype, as: :select, collection: [ "Продажа", "Покупка", "Обмен", "Услуга", "Аренда"]
    .form-inputs
      = f.input :image, as: :file, multiple: true
    .form-actions
      = f.button :submit

app/views/adverts/_new_form.html.slim
div.col-md-6
  = simple_form_for(@advert, action: :upload, :html => {multipart: true}) do |f|
    - if @advert.errors.any?
      #error_explanation
        h2 = "#{pluralize(@advert.errors.count, "error")} prohibited this advert from being saved:"
        ul
          - @advert.errors.full_messages.each do |message|
            li = message

    .form-inputs
      = f.input :title
    .form-inputs
      = f.input :description
    .form-inputs
      = f.input :price
    .form-inputs
      = f.association :category
    .form-inputs
      = f.input :adverttype, as: :select, collection: [ "Продажа", "Покупка", "Обмен", "Услуга", "Аренда"]
    .form-inputs
      = f.input :image, as: :file, multiple: true
    .form-actions
      = f.button :submit

app/views/adverts/edit.html.slim
h1 Editing advert
- if current_user.email == "biginf.com@gmail.com"
	== render 'admin_form'
- else 
	== render 'form'
= link_to 'Show', @advert
'|
= link_to 'Back', adverts_path

app/views/adverts/index.html.slim
div.container
  h1 Listing adverts
  div.form-group
  = search_form_for (@q) do |f|
    .form-group
      = f.search_field :title_cont  
    .form-actions
      = f.button :submit
  br/   
  table.table.table-striped
    thead
      tr.warning
        th Title
        th Description
        th
          p = sort_link(@q, :price, 'Price', default_order: :desc)
        th Category
        th Type
        th
        th
        th
        th Image
        th
          p = sort_link(@q, :updated_at, 'LastUp', default_order: :desc)
        th Status
        th Go to Draft



    tbody
      - @adverts.each do |advert|
        tr
          td = advert.title
          td = advert.description
          td = advert.price
          td = advert.category.title
          td = advert.adverttype
          td = link_to 'Show', advert
          td = link_to 'Edit', edit_advert_path(advert)
          td = link_to 'Destroy', advert, data: {:confirm => 'Are you sure?'}, :method => :delete
          td = image_tag("#{advert.image.url}", class: "img-responsive", width: "150")
          td = advert.updated_at
          td = advert.status
          td = link_to 'to Draft', to_draft_adverts_path

          

  br/
  = will_paginate @adverts
  br/
  = link_to 'New Advert', new_advert_path

app/views/adverts/new.html.slim
h1 New advert

== render 'new_form'

= link_to 'Back', adverts_path

app/views/adverts/show.html.slim
p
  strong Title:
  = @advert.title
p
  strong Description:
  = @advert.description
p
  strong Price:
  = @advert.price
p
  strong User-email:
  = @advert.user_id
p
  strong Status:
  = @advert.status
  





br/
= link_to 'Edit', edit_advert_path(@advert)
'|
= link_to 'Back', adverts_path

app/views/adverttypes/_form.html.slim
= simple_form_for(@adverttype) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title

  .form-actions
    = f.button :submit

app/views/adverttypes/edit.html.slim
h1 Editing adverttype

== render 'form'

= link_to 'Show', @adverttype
'|
= link_to 'Back', adverttypes_path

app/views/adverttypes/index.html.slim
h1 Listing adverttypes

table
  thead
    tr
      th Title
      th
      th
      th

  tbody
    - @adverttypes.each do |adverttype|
      tr
        td = adverttype.title
        td = link_to 'Show', adverttype
        td = link_to 'Edit', edit_adverttype_path(adverttype)
        td = link_to 'Destroy', adverttype, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Adverttype', new_adverttype_path

app/views/adverttypes/new.html.slim
h1 New adverttype

== render 'form'

= link_to 'Back', adverttypes_path

app/views/adverttypes/show.html.slim
p#notice = notice

p
  strong Title:
  = @adverttype.title

= link_to 'Edit', edit_adverttype_path(@adverttype)
'|
= link_to 'Back', adverttypes_path

app/views/categories/_form.html.slim
= simple_form_for(@category) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title

  .form-actions
    = f.button :submit

app/views/categories/edit.html.slim
h1 Editing category

== render 'form'

= link_to 'Show', @category
'|
= link_to 'Back', categories_path

app/views/categories/index.html.slim
h1 Listing categories

table.table
  thead
    tr
      th Title
      th
      th
      th

  tbody
    - @categories.each do |category|
      tr
        td = category.title
        td = link_to 'Show', category
        td = link_to 'Edit', edit_category_path(category)
        td = link_to 'Destroy', category, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Category', new_category_path

app/views/categories/new.html.slim
h1 New category

== render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.slim
p#notice = notice

h1
  strong Title:
  = @category.title

= link_to 'Edit', edit_category_path(@category)
'|
= link_to 'Back', categories_path

br/
table.table.table-striped
    thead
      tr.warning
        th Title
        th Description
        th Price
        th
        th
        th
        th Image

    tbody
      - @category.adverts.each do |advert|
        tr
          td = advert.title
          td = advert.description
          td = advert.price
          td = link_to 'Show', advert
          td = link_to 'Edit', edit_advert_path(advert)
          td = link_to 'Destroy', advert, data: {:confirm => 'Are you sure?'}, :method => :delete
          td
            img src="#{advert.image}"/

app/views/dashboard/_admin_dashboard.html.slim
div.container
  h1 Listing adverts
  div.form-group
  = search_form_for (@q) do |f|
    .form-group
      = f.search_field :title_cont  
    .form-actions
      = f.button :submit
  br/   
  table.table.table-striped
    thead
      tr.warning
        th Title
        th Description
        th
          p = sort_link(@q, :price, 'Price', default_order: :desc)
        th
        th
        th
        th Image
        th Category
        th
          p = sort_link(@q, :updated_at, 'LastUp', default_order: :desc)
        th Status
        th User
        th Go to Draft



    tbody
      - @adverts.each do |advert|
        tr
          td = advert.title
          td = advert.description
          td = advert.price
          td = link_to 'Show', advert
          td = link_to 'Edit', edit_advert_path(advert)
          td = link_to 'Destroy', advert, data: {:confirm => 'Are you sure?'}, :method => :delete
          td = image_tag("#{advert.image}",height: '32', width: '32', class: "img-rounded")
          td = advert.category.title
          td = advert.updated_at
          td = advert.status
          td = advert.user.email
          td = link_to 'to Draft', :method => :draft
          

  br/
  = will_paginate @adverts
  br/
  = link_to 'New Advert', new_advert_path

app/views/dashboard/_dashboard.html.slim
h1 dgsfg

div.container
  h1 Listing adverts
  div.form-group
  = search_form_for (@q) do |f|
    .form-group
      = f.search_field :title_cont  
    .form-actions
      = f.button :submit
  br/   
  table.table.table-striped
    thead
      tr.warning
        th Title
        th Description
        th
          p = sort_link(@q, :price, 'Price', default_order: :desc)
        th Category
        th
        th
        th
        th Image
        th Category
        th
          p = sort_link(@q, :updated_at, 'LastUp', default_order: :desc)
        th Status
        th Go to Draft



    tbody
      - current_user.adverts.each do |advert|
        tr
          td = advert.title
          td = advert.description
          td = advert.price
          td dddd
          td = link_to 'Show', advert
          td = link_to 'Edit', edit_advert_path(advert)
          td = link_to 'Destroy', advert, data: {:confirm => 'Are you sure?'}, :method => :delete
          td = image_tag("#{advert.image}",height: '32', width: '32', class: "img-rounded")
          td advert category title
          td = advert.updated_at
          td = advert.status
          td = link_to 'to Draft', :method => :draft
          

  br/
  = will_paginate @adverts
  br/
  = link_to 'New Advert', new_advert_path

app/views/dashboard/in_draft.html.slim
div.container
  h1 Listing adverts
  
  br/   
  table.table.table-striped
    thead
      tr.warning
        th Title
        th Description
        th Price
        th
        th
        th
        th Image
        th Category
        th Update at
        th Status
        th User
        th Go to Draft



    tbody
      - @adverts.each do |advert|
        tr
          td = advert.title
          td = advert.description
          td = advert.price
          td = link_to 'Show', advert
          td = link_to 'Edit', edit_advert_path(advert)
          td = link_to 'Destroy', advert, data: {:confirm => 'Are you sure?'}, :method => :delete
          td = image_tag("#{advert.image}",height: '32', width: '32', class: "img-rounded")
          td = advert.category.title
          td = advert.updated_at
          td = advert.status
          td = advert.user.email
          td = link_to 'to Draft', :method => :draft
          


  br/
  = link_to 'New Advert', new_advert_path

app/views/dashboard/index.html.slim
h1 Dashboard
- if current_user.email == "biginf.com@gmail.com"
	== render 'admin_dashboard'
- else 
	== render 'dashboard'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Board2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  	<div class="container-fluid">
		<ul class="nav navbar-nav">
	        <li><%= link_to "All advert", adverts_path %></li>
	        <li><%= link_to "Category", categories_path %></li>
	        <li><%= link_to "Dashboard", dashboard_index_path %></li>
	        <li><%= link_to "In Draft", in_draft_dashboard_index_path %></li>
	      </ul>

	      <div class="navbar-right" id="top-button">
			<% if user_signed_in? %>
				<ul class="nav navbar-nav">
					<li id="notyou">Signed in as <%= current_user.email %>. Not you? </li>
					<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
					<li><%= link_to "Add new advert", new_advert_path %></li>
				</ul>
			<% else %>
				<ul class="nav navbar-nav">
					<li><%= link_to "Sign up", new_user_registration_path %></li> 
					<li><%= link_to "Sign in", new_user_session_path %></li>
				</ul>
			<% end %>
		</div>

	</div>
</nav>

<% flash.each do |name, msg| %>
		<%= content_tag :div, msg, :id => "flash_#{name}" %>
	<% end %>


<div class="container">
	<%= yield %>
</div>
</body>
</html>

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :email
    = f.text_field :email
  .actions = f.submit

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

= link_to 'Show', @user
'|
= link_to 'Back', users_path

app/views/users/index.html.slim
h1 Listing users

table
  thead
    tr
      th Email
      th
      th
      th

  tbody
    - @users.each do |user|
      tr
        td = user.email
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice = notice

p
  strong Email:
  = @user.email

= link_to 'Edit', edit_user_path(@user)
'|
= link_to 'Back', users_path